project:
  type: website
  resources:
    - assets/
    - www/
  render:
    - "*.qmd"
    # - "!cmip6-processing.qmd"
execute:
  freeze: auto  # re-render only when source changes
  cache: true
  
website:
  title: "Rotorua Lake Modelling"
  # llms-txt: true
  site-path: "/rotorua-pc10/"
  favicon: www/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: targets.qmd
        text: Targets
      - href: resources.qmd
        text: Resources
      - href: notes.qmd
        text: Notes
      - href: gantt.qmd
        text: GANTT
      - icon: github
        href: https://github.com/tadhg-moore/rotorua-pc10
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Project Overview"
        href: index.qmd
        contents:
          - gantt.qmd
          - href: modelling-updates.qmd
            text: "Modelling Updates"
      - section: "Lake Models"
        contents:
          - href: rotorua-glm-config.qmd
            text: "GLM Config"
          - href: rotorua-glm-config_v4.qmd
            text: "GLM Config (v4)"
          - href: rotorua-inflows.qmd
            text: "Inflows"
          - href: light-data.qmd
            text: "Light Data (Kw)"
          - href: plot-rotorua.qmd
            text: "Output Plots (v4)"
          - href: aed_calibration_sa_plan.qmd
            text: "Calibration & SA Plan"
      - section: "Alum Dosing"
        contents:
          - href: alum-model.qmd
            text: "Alum Model"
          - href: aed-alum-module.qmd
            text: "Simplified Alum Module"
          - href: glm_aed_alum_stress_tests.qmd
            text: "GLM-AED aed_alum Stress Tests"
          - href: alum-dosing-sanila-msc-thesis.qmd
            text: "Sanila Thesis Notes"
      - section: "Tasks"
        contents:
          - data.qmd
          - data-request.qmd
          - cmip6-processing.qmd
          - cmip6-visualisation.qmd
      - section: "Notes"
        contents:
          - href: notes.qmd
            text: "Meeting Notes"
  page-footer: 
    left: 
      - text: "Rotorua Plan Change 10" 
        href: "https://www.boprc.govt.nz/your-council/plans-and-policies/plans/regional-plans/regional-natural-resources-plan/lake-rotorua-nutrient-management-plan-change-10/"
    right: |
      <a href="https://github.com/tadhg-moore/rotorua-pc10" style="margin-right: 10px;">
        <i class="bi bi-github" style="font-size: 1.3em;"></i>
      </a>
      <a href="https://www.boprc.govt.nz/">
        <img src="www/boprc-logo.png" alt="Bay of Plenty Logo" style="height: 32px; vertical-align: middle;">
      </a>

format:
  html:
    theme: cosmo
    css: www/styles.css
    toc: true
    lightbox: true
    code-fold: true
    code-tools: true
    