name: Render and Publish Quarto Website

on:
  push:
    branches: [main]     # or 'master'
  pull_request:
  workflow_dispatch:      # allow manual trigger

permissions:
  contents: write         # needed to publish to GitHub Pages

jobs:
  build-deploy:
    runs-on: windows-latest
    env:
      R_KEYRING_BACKEND: basic
      ONEDRIVE_TOKEN_ENCRYPTED: ${{ secrets.ONEDRIVE_TOKEN_ENCRYPTED }}
      ONEDRIVE_TOKEN_PASSWORD: ${{ secrets.ONEDRIVE_TOKEN_PASSWORD }}
      ONEDRIVE_TOKEN_HASH: ${{ secrets.ONEDRIVE_TOKEN_HASH }}
      LERNZMP_KEY: ${{ secrets.LERNZMP_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.8.23"     # use latest stable

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # - name:  Install dependencies
      #   run:   |
      #    if [ "$RUNNER_OS" == "Linux" ]; then
      #         sudo apt-get update
      #         sudo apt-get install -y \
      #           libudunits2-dev \
      #           libgdal-dev \
      #           libgeos-dev \
      #           libproj-dev \
      #           libsecret-1-dev \
      #           libglpk40 \
      #           libnode-dev       # ← add this
      #     fi

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv/cache
          key: ${{ runner.os }}-renv-v2-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Install renv
        run: Rscript -e 'install.packages("renv")'
      
      - name: Restore renv packages
        run: Rscript -e 'renv::restore(prompt = FALSE)'
          
      - name: Render site
        run: quarto render website   # use 'website' dir

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
